name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build jar
        run: mvn clean package -DskipTests

      - name: Upload jar to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/api-0.0.1-SNAPSHOT.jar"
          target: "/opt/backend/app.jar"
          strip_components: 1

      - name: Rename jar
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mv /opt/backend/*.jar /opt/backend/app.jar
            chown springboot:springboot /opt/backend/app.jar
            systemctl restart backend